# Use root/example as user/password credentials
version: '3.1'

services:
# relational db host
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - myapp:/var/lib/mysql
    ports:
      - 3306:3306
# relational db admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes: 
  myapp: